Repository divyansh-2005/my-calendar-app, pull requests merged in 2024-10, with the labels that each got.

#8 #3 Solved . I have done the necessary UI/UX change
  FRONTEND/package-lock.json
  FRONTEND/package.json
  FRONTEND/postcss.config.js
  FRONTEND/src/App.jsx
  FRONTEND/src/index.css
  FRONTEND/src/pages/Homepage.jsx
  FRONTEND/src/styles/ExpenseBox.css
  FRONTEND/src/styles/ToDoBox.css
  FRONTEND/tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#11 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#17 Validation added in authentication
  BACKEND/controllers/authController.js
  BACKEND/package-lock.json
  BACKEND/package.json
  BACKEND/routes/authRoutes.js
  BACKEND/utils/validation/auth.js
  FRONTEND/src/components/Navbar.jsx
  FRONTEND/src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#22 Enhance Readme.md file #16
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#23 Changed Login and Register UI
  FRONTEND/src/images/Auth2.jpg
  FRONTEND/src/pages/LoginPage.jsx
  FRONTEND/src/pages/RegisterPage.jsx
  FRONTEND/src/styles/Login.css
  FRONTEND/src/styles/Register.css
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#24 adding CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#26 Footer
  FRONTEND/package-lock.json
  FRONTEND/package.json
  FRONTEND/src/App.jsx
  FRONTEND/src/components/Footer.jsx
  FRONTEND/tailwind.config.js
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#32 Todo page fix
  FRONTEND/src/pages/ExpensePage.jsx
  FRONTEND/src/pages/ToDoPage.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#44 Writing the Common AsyncHandler Utility
  BACKEND/controllers/authController.js
  BACKEND/utils/ApiError.js
  BACKEND/utils/ApiResponse.js
  BACKEND/utils/AsyncHandler.js
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#48 [BUG]Changing the old twitter to new X svg. #42
  FRONTEND/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest, level 1

#59 Add user profile page issue#21
  BACKEND/controllers/todoController.js
  FRONTEND/src/App.jsx
  FRONTEND/src/components/Navbar.jsx
  FRONTEND/src/pages/UserProfile.jsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#60 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#62 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1

#77 Fixed Add Expense
  BACKEND/controllers/authController.js
  BACKEND/controllers/expenseController.js
  BACKEND/models/Expense.js
  BACKEND/package-lock.json
  BACKEND/package.json
  BACKEND/routes/expenseRoutes.js
  BACKEND/utils/AsyncHandler.js
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#70 Sucessfully added and linked AboutUs and ContactUs Pages #55
  FRONTEND/src/App.jsx
  FRONTEND/src/components/Footer.jsx
  FRONTEND/src/pages/AboutUsPage.jsx
  FRONTEND/src/pages/ContactUs.jsx
  FRONTEND/src/styles/AboutUs.css
  FRONTEND/src/styles/ContactUs.css
Labels: gssoc-ext, hacktoberfest-accepted, level 3

#111 added changes in month
  FRONTEND/src/components/Calendar.jsx
  FRONTEND/src/styles/Calendar.css
Labels: gssoc-ext, hacktoberfest-accepted, level 1
